### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by liweibingzhang** [longranger2/Quick-Calculation-Correction#2]

**Comment by YuanYe-99** [comment]
> _No description provided._

请问你有这个label.txt或者formula.txt了吗？

**Comment by liweibingzhang** [comment]
> > _No description provided._
> 
> 请问你有这个label.txt或者formula.txt了吗？

有的，但是因为项目整体时间比较久远，加上逆波兰式在我调试的时候代码有问题，所以我这边还是没法运行这个项目，放弃了hhh
