### ISSUE TITLE
如何部署呢？

### ISSUE THREAD

**Issue by YuanYe-99** [longranger2/Quick-Calculation-Correction#3]
非常感谢你的工作！
请问是yolo这个文件夹用于部署吗？我想在我自己的电脑上部署试一下，但不太明白项目哪个是用于部署的，哪个才是训练好的模型。
期待你的回复和帮助！

**Comment by longranger2** [comment]
这个项目比较早的了，当时这个项目维护得也不是很好，具体细节不太清楚了。这个项目主要由两个功能组成：YOLO用来识别位置，CRNN用来提取内容。所以YOLO文件夹是用来放置YOLO算法相关的代码，CRNN是用来放置CRNN相关的代码。还有我当时是直接基于本地运行的，也没有部署到服务器去运行过

**Comment by longranger2** [comment]
当时主要基于这两个项目去进行整合的，代码方面你看看这个或许好些：

- https://github.com/zhijiezhong/crnn/tree/master
- https://github.com/bubbliiiing/yolo3-pytorch

**Comment by YuanYe-99** [comment]
> @YuanYe-99 这个项目比较早的了，当时这个项目维护得也不是很好，具体细节不太清楚了。这个项目主要由两个功能组成：YOLO用来识别位置，CRNN用来提取内容。所以YOLO文件夹是用来放置YOLO算法相关的代码，CRNN是用来放置CRNN相关的代码。还有我当时是直接基于本地运行的，也没有部署到服务器去运行过

我尽力去尝试修改代码，目前能运行起来，但预测结果存在问题，好像是检测的问题。
（百度网盘上的模型GPU.pt和CPU.pt的需要使用吗？是放在什么目录下？）[
<img width="608" alt="屏幕截图 2024-07-07 232724" src="https://github.com/longranger2/Quick-Calculation-Correction/assets/55839766/86932527-15b9-4088-9317-952ccb6b14e0">
<img width="563" alt="屏幕截图 2024-07-07 232740" src="https://github.com/longranger2/Quick-Calculation-Correction/assets/55839766/c7dca247-3e97-4ef4-a769-0cf222eae639">
](url)

**Comment by longranger2** [comment]
CPU.pt和GPU.pt，一个是CPU版本的权重，另一个是GPT版本的权重

**Comment by longranger2** [comment]
labels.txt的参数没有记错的话就是加减乘除这些，貌似还有括号
`
+
-
×
÷
(
)

`

**Comment by YuanYe-99** [comment]
> labels.txt的参数没有记错的话就是加减乘除这些，貌似还有括号 <img alt="image" width="35" src="https://private-user-images.githubusercontent.com/52858395/346531918-6811a3f7-dd81-4c2b-970b-5961deffcf4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDQ1NzAsIm5iZiI6MTcyMDQ0NDI3MCwicGF0aCI6Ii81Mjg1ODM5NS8zNDY1MzE5MTgtNjgxMWEzZjctZGQ4MS00YzJiLTk3MGItNTk2MWRlZmZjZjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEzMTExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDJhNjc3ZjNjZTBkYjIzMjBhNTk1MDlmY2NlNGI0Yjk2MmZmYjA0Y2Q5ZGFiNDFiMzZjMDBhMWIxYTRjMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qYopgC7w26cHdhi8hiIHkJxcmPvq3C_PA43VzGWNlXQ">

非常感谢你的帮助！

**Comment by longranger2** [comment]
不客气，如果你跑通项目且愿意的话也可以一起来完善下这个项目哈～（后面打算完善下，不过最近在忙其他事情，可能没有那么快hh）
